[platformio]
default_envs = esp32s3
src_dir = main

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200

; Keep sdkconfig defaults from repository
board_build.sdkconfig_path = sdkconfig.defaults

; Match esp32-s3-devkitc-1-n8 default flash size
board_upload.flash_size = 8MB

build_flags =
    -D WIFI_SSID=\"ESP32S3-USB-DISK\"
    -D WIFI_PASS=\"12345678\"
